on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release Build Package
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Cardinal-Editor build
        uses: actions/download-artifact@v4
      - name: Rename build with tag
        run: |
          ls -R
          mv cardinal-editor.zip cardinal-editor-${{ github.event.release.tag_name }}.zip
      - name: Publish Build to corresponding Github Release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'cardinal-editor-${{ github.event.release.tag_name }}.zip'
